# Users
User.create!(name:  "Cerisa",
             email: "cerisa@strangerelics.com",
             password:              "password",
             password_confirmation: "password",
             admin:     true,
             activated: true,
             activated_at: Time.zone.now)

Character.create!(
  name: "Claire",
  archetype: "Ally",
  goal: "the World-Tree",
  motive: "protect Saanvi",
  brave: 1,
  fierce: -1,
  wary: 1,
  clever: 0,
  strange: 2,
  experience: 2,
  posessions: "An old flute, passed down from my mother\nA handful of coins",
  losses: "My family",
  pride: false,
  health: true,
  strength: false,
  hope: false,
  life: false,
  return_brave: false,
  return_strange: true,
  return_different: false,
  dead: false,
  unprepared: true,
  notes: "Nobody too special",
  look: "Meek",
  virtue_noble: true,
  virtue_strong: false,
  virtue_unassuming: true,
  virtue_practical: false,
  virtue_weird: true) 